Update ben-bot-CI.yml
make lint not fail the entire thing

Signed-off-by: KindKid <kindkid27@pm.me>

diff --git a/.github/workflows/ben-bot-CI.yml b/.github/workflows/ben-bot-CI.yml
--- a/.github/workflows/ben-bot-CI.yml
+++ b/.github/workflows/ben-bot-CI.yml
@@ -23,7 +23,7 @@ jobs:
         run: npm install
 
       - name: Lint code
-        run: npm run lint
+        run: npm run lint || echo "::warning::Linting failed (non-blocking)"
 
       - name: Clear log and cache files
         run: |
